/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jgbffgckrhiqshkogvia"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnYmZmZ2NrcmhpcXNoa29ndmlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4NjEwMDQsImV4cCI6MjA4OTQzNzAwNH0.8UGwa7fM2Oi_teXdTwHR-3dLfVp53kNkS0EWI-YLhFY"